### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by reitzig** [reitzig/ltx2any#116]
Set up automated testing and deployment:

 1. Run tests against
   * Ruby versions 2.3, 2.4, 2.5;
   * GNU/Linux and TeXlive;
   * macOS and MacTeX (?);
   * Windows and MiKTeX/proTeXt (?).
 2. Build and deploy docs (if applicable).
 3. Build and deploy gem (if commit tagged).

Start off with Linux+TeXlive; add other platforms later if feasible.

**Comment by koppor** [comment]
I love CircleCI. Straight-forward config:
https://github.com/latextemplates/scientific-thesis-template/blob/master/.circleci/config.yml

It should be possible to use multiple docker images...

Am Di., 13. Nov. 2018, 19:41 hat Raphael R. <notifications@github.com>
geschrieben:

**Comment by reitzig** [comment]
I've used CicleCI before for texlogparser, but they seem to have limited support for macOS builds, and none for Windows.

I've also used Travis, but couldn't get gem deployment to work earlier this year.

I'll see what the situation is when I get to this.

**Comment by koppor** [comment]
@reitzig Not sure if there should be another CI issue for i) deploy docs and ii) deploy gem.

**Comment by reitzig** [comment]
If there _was_ a gem, sure ... 🙊

This project is so far from best practice, it's hard to even start cleaning it up. 😅
