### ISSUE TITLE
Current version doesn't work on ArchLinux

### ISSUE THREAD

**Issue by kayb94** [reitzig/ltx2any#117]
Hi,

when I clone the latest version, it does not work on Arch Linux:
<pre>$ ./ltx2any 
<font color="#FFFFFF"><b>Traceback</b></font> (most recent call last):
	2: from ./ltx2any.rb:37:in `&lt;main&gt;&apos;
	1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require&apos;
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require&apos;: <font color="#FFFFFF"><b>cannot load such file -- bundler (</b></font><font color="#FFFFFF"><u style="text-decoration-style:single"><b>LoadError</b></u></font><font color="#FFFFFF"><b>)</b></font></pre>

"ltx2any 0.9a" works (commit 76f69b32f12fd0449d75233aa6b9942fac0f515e, 24. February 2018). I can't say, at what particular commit it stopped working.

Regards

**Comment by reitzig** [comment]
I think running `gem install bundler` should solve this. Proceed installing any other gems that may be missing.

NB: The tool will be deployed as gem in the future, getting rid of such issues. Sadly, time and motivation is rather limited. :/

**Comment by reitzig** [comment]
No reponse, so the issue apparently resolved itself one way or another.
