### ISSUE TITLE
Add detail to Windows installation tips

### ISSUE THREAD

**Issue by tylerdq** [reitzig/ltx2any#119]
In addition to the steps outlined [here](https://github.com/reitzig/ltx2any/wiki#tips-for-windows), I also had to take the following steps to resolve dependencies:

1. `gem install bundler`
2. `bundle check`
3. `bundle update --bundler`

I think listing these steps could help other first-time Ruby users like myself.

**Comment by reitzig** [comment]
Ah, yes, thanks for calling me on that. I _thought_ I updated the wiki after #117 but it seems I didn't.

Is it better now, or do you think Windows needs special treatment?

(FWIW, I have pending work to make a gem out of this, which simplifies the whole process. No ETA, alas.)

**Comment by tylerdq** [comment]
No worries, I think it makes sense now. I also edited the wiki just now to add a link to the bundler website as a hint to those who may not be familiar with ruby dependency management.
