### ISSUE TITLE
Excessive Directory Nesting Issue in ltx2any.rb on Windows

### ISSUE THREAD

**Issue by Foadsf** [reitzig/ltx2any#125]
## Description
As I have also explained [here](https://stackoverflow.com/q/77880877/4999991), I'm encountering an issue with the `ltx2any.rb` script, which creates excessively nested directories when running on Windows. This seems to occur during the execution of the `copy2tmp` method, which leads to a deeply nested directory structure like `../folderName/folderName/folderName/...`, eventually causing a "No such file or directory" error.

The command I run is

ruby "C:\Users\Foo\OneDrive - Bar\Desktop\Apps\ltx2any\ltx2any.rb" -t build main.tex

and the error message I get is

~~~
[ltx2any] Copying files to tmp ... Error

[ltx2any] Error: No such file or directory @ dir_s_mkdir - build/../01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test/01_test
          See main.err for details.
~~~

## Steps to Reproduce
1. Run the `ltx2any.rb` script to process a LaTeX document.
2. Observe the creation of deeply nested directories during the process.

## What I Tried
- **Added Debugging**: Implemented debugging statements to track recursion depth in the `copy2tmp` method.
- **Manual Inspection**: Checked for symbolic links or unusual directory structures. Found no clear issues here.
- **Reviewing Method Calls**: Ensured that `copy2tmp` was called with appropriate parameters and reviewed its recursive calls.

## Expected Behavior
The script should copy files to a temporary directory without creating an unnecessary nested structure.

## Actual Behavior
The script creates a deeply nested directory path, resulting in a file system error due to the path length or structure.

## Environment
- Operating System: Windows
- Ruby Version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

## Additional Information
I am attaching the modified `ltx2any.rb` script for reference. Any insights or suggestions to resolve this issue would be greatly appreciated.

## Modified Script
[Attachment: modified `ltx2any.rb` script](https://github.com/reitzig/ltx2any/files/14053673/ltx2any.zip)

**Comment by Foadsf** [comment]
I just sent a pull request [here](https://github.com/reitzig/ltx2any/pull/126) that should solve this problem.

**Comment by reitzig** [comment]
Thanks for the report, and the PR!

FWIW, I find it hard to understand the issue from your description alone. An MWE would be appreciated or, failing that, a clear example. I _can't_ run anything on Windows! 😅

That said, given the feedback other users provided on #126, I reckon this is a real issue and your fix looks good to me. Thanks!
