### ISSUE TITLE
Name undefined control sequence

### ISSUE THREAD

**Issue by koppor** [reitzig/ltx2any#91]
Is it possible to extract some kinds of error messages "better"?

For instance, at "undefined control sequence", I'd like to know the control sequence instead of some other (more or less) unrelated information. 😇 

![grabbed_20170131-102653](https://cloud.githubusercontent.com/assets/1366654/22459181/e5c6db12-e79f-11e6-8ecc-f3a7689d6aa1.png)

**Comment by akerbos** [comment]
Phew, LaTeX logs *suck*.

Basically, [TeXLogParser](https://github.com/akerbos/ltx2any/blob/master/lib/TeXLogParser.rb) is the best I can do short of dealing with even more special cases.

That said, this looks like a standard error; of such, TeXLogParser *should* catch the whole message without changing formatting, which usually give you a helpful message. Can you paste the passage from the raw log, please?

**Comment by reitzig** [comment]
@koppor Is this still current? Without a concrete log as an example, I won't be able to add more rules to the log parser.

**Comment by koppor** [comment]
In case I come up with an [mwe](https://stackoverflow.com/help/mcve), I will reopen the issue.
